### ISSUE TITLE
Issues with geo-dash and two date steps for Digital Globe imagery

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#109]
Hello again Gary,
I am looking at the project  called CEO Manual Test Project, under the US Forest Service Institution, and am running into two issues. 
1. I am still not getting the Geo-Dash time series charts to load. 
2. I also was looking at the images from digital globe - we have one feed set up to load images before 2012 and another for 2016. However all the images that load are the same. Did we set up the imagery feed incorrectly or is this a new bug. I feel like it was working fine just the other week.
Thanks,
Karis

**Comment by lambdatronic** [comment]
Hi Karis,

I took a look at your project, and here's what I'm seeing:
1. There appears to be some bugs in Billy's geo-dash.js code. I've attached a screenshot of what I'm seeing on my side. You can see any page errors by opening your web browser's developer tools and checking the Console tab. This is usually accessible via F12 in Firefox and Chrome.

2. I checked both of your imagery feeds, and you set them up correctly. There are no bugs showing up in the developer console, so everything appears to be operating correctly. I suspect what you are experiencing here is an unfortunate temporal sparseness in DigitalGlobe's imagery catalog. Both of the imagery sources have been configured to pull the most recent tiles before their respective cut-off dates. The DigitalGlobe (2016) layer uses acquisition_date<'2016-12-31'. The DigitalGlobe <2012 layer uses acquisition_date<'2012-01-01'. My guess would be that DigitalGlobe only has imagery for that project location from before 2012-01-01 as this would make both queries return identical tiles. Unfortunately this isn't something that I can fix, since it's up to DG to add more data to their catalog. To be honest, I've been running into a number of annoyances with the available imagery recently, and it will be one of my primary conversation points while in Rome next week. I'll keep you updated on what we find out.
![screenshot-20171011](https://user-images.githubusercontent.com/173350/31465553-4b160e06-aea2-11e7-9684-25e975fc5714.png)

**Comment by billyz313** [comment]
Hi Karis,
It looks like the image collection name was incorrect.  I changed it to LANDSAT/LE7_L1T_32DAY_NDVI and it works now.

**Comment by karistenneson** [comment]
That would do it. Thanks for catching our typo.
