### ISSUE TITLE
Suggestions: joining/managing organizations

### ISSUE THREAD

**Issue by bmschwert** [openforis/collect-earth-online#113]
-A user should be able to request joining an organization as either a member OR an admin (currently they are not able to specify desired role)
-A user who is a member of an organization should be able to see which members are admins
-A user should receive notification when their pending status is switched to confirmed member for an organization
-An organization's admin should receive notification when a user has requested membership

**Comment by snasaio** [comment]
WIth PR #217 a member will be able to see which users are admins and memebers

**Comment by lambdatronic** [comment]
I'd rather not have users request admin status directly, since the admin that adds them to the group can easily choose their membership level at join time. Matt has also mentioned that the second bullet point above was resolved some time ago.

We still need to implement the two notifications described by the OP.

**Comment by sirmspencer** [comment]
I think a user does get an email when the status change from->to anything so that would cover point 3.  Notifying the admins upon request is a good feature to add.
