### ISSUE TITLE
New WMS image source not working

### ISSUE THREAD

**Issue by khanalshiva** [openforis/collect-earth-online#124]
Hi,

I had set up s WMS feed and also added two different years of available imagery following the CEO Manual V2 guidelines.   Until yesterday I could see image from those options but now has stopped loading images. The default imagery options like 'DigitalGlobeRecentImagery" is working but not the ones that I set up.  Would appreciate any help.

Thank you.

**Comment by lambdatronic** [comment]
We experienced a temporary outage for the DigitalGlobeWMSImagery source starting on Thursday afternoon. This was due to an invalid CONNECTID generated by the DigitalGlobe Cloud Services team. A valid CONNECTID has now been installed in the site for that layer, so it should work correctly going forward. Please be aware that the DigitalGlobeWMSImagery layer will become private sometime this month and will only be available to SERVIR-related institutions going forward, due to a recent decision by NASA (the organization which funds that imagery source).
