### ISSUE TITLE
No project found with ID 0

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#134]
I just went into collect.earth and tried to create a new project. Every time I click the Create New Project button, the error "No project found with ID 0" pops up and I am unable to create a project.

**Comment by lambdatronic** [comment]
Thanks for reporting this, Randy. It looks like this bug was introduced during the recent database merge between ceo.sig-gis.com and collect.earth. The merging scripts that I wrote apparently only copied over the "real" projects from both sites into the new combined database. Project 0 (the one causing the error) is an empty template project used to initialize the form fields on the project creation page.

I manually added Project 0 to the new collect.earth database, and now it seems to be working correctly again. Please let me know if you notice anything else behaving strangely on the site since the database merge.

Thanks,
  Gary
