### ISSUE TITLE
Viewing and recording imagery dates 

### ISSUE THREAD

**Issue by africaf** [openforis/collect-earth-online#428]
See dates of the imagery used to collect data, it could be extracted from the metadata of the data sources that provide this (all publicly datasets available in GEE) and include dates of image source in the csv files containing all data collected.

**Comment by sirmspencer** [comment]
This should already be included in the raw data output (not the aggregate output). Can you provide an example where this is not working as expected?

**Comment by sirmspencer** [comment]
From @karistenneson 
Record imagery date associated with imagery when survey questions are answered. For imagery sources (e.g. Planet NICFI) where dates are available, record both imagery source and date. For those without dates, record only imagery source. I think this is an expansion of the functionality in SecureWatch.

As far as I understand, the imagery is only recorded once per sample. So they would need to do two projects to record multiple dates. This may also be something to think about in the future, although I know the database changes might be significant.

Request from Ecuador team among others. This feature is included in E.7 funding if awarded.

**Comment by sirmspencer** [comment]
Im closing this due to a lack of specificity.  The raw csv output already includes imagery attributions at the time of collection.

If you want a summary at the plot level like do at the plot level for secure watch please open a ticket with more details on what you need.

If E.7 is awarded we will need to make issues to address the contract.
