### ISSUE TITLE
GeoDash opening in same tab when moving to new plot 

### ISSUE THREAD

**Issue by africaf** [openforis/collect-earth-online#431]
Not automatic viewing the GeoDash window when moving to new plot. Now GeoDash is not opening in a different tab but in the same tab where plot should appear.

**Comment by lambdatronic** [comment]
Hi Africa. This sounds like a user error that can occasionally happen
if you are cutting and pasting URLs in your browser.

When navigating through the collection page, a new tab will be opened
to display the GeoDash if one has been configured for your project.
From a technical perspective, the browser assigns names to these tabs.
The name of the GeoDash tab is "_geodash" (this is set by CEO to
unique identify it).

Each time you navigate to a new plot on the collection page, CEO sends
a message to the "_geodash" tab to redisplay the GeoDash widgets for
the new plot.

If you copy your CEO URL (e.g., for the collection page) into the
"_geodash" tab, then when you try to visit a new plot, CEO will
disappear and the GeoDash widgets will be displayed in that same tab.
We have to use a named "_geodash" tab to keep the GeoDash widgets in
one place. Otherwise, they would spawn a new tab for every single plot
that you visit.

All you have to do to avoid this situation is to not copy your CEO
URLs into an open GeoDash tab.
