### ISSUE TITLE
duplicate point info in Sample Design causes sample points to drop

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#441]
If you upload a csv for your sample point design after specifying the number of samples per plot, your project will have no sample points. See project https://collect.earth/collection?projectId=6527

Steps: 
1. Plot design: upload CSV with sample plot information.
2. Sample design: click radio button for random, and specify some number of samples per plot.
3. Then switch the radio button to "upload CSV" and upload a csv with sample point locations.

**Comment by kdyson** [comment]
![image](https://user-images.githubusercontent.com/6980290/78314191-132e1300-750e-11ea-9136-26da7f8130ed.png)

**Comment by biplovbhandari** [comment]
Those samples and plots are imported good in the system. The only issue is that you specified the plot size to be very small to contain those samples. You can still view them when you zoom out at the above project. Checking this at the server end will be costly especially when the shape and the number of plots and samples increase.

**Comment by kdyson** [comment]
@biplovbhandari this project uses the same csvs and doesn't have the same issue? https://collect.earth/collection?projectId=6544

**Comment by biplovbhandari** [comment]
I think its the matter of specifying the distance with either the plots or samples. For example, this is the params that I have set up with the same CSVs for this [project](https://collect.earth/collection?projectId=7133) so that my samples diameter is enough to contain my plots.

![image](https://user-images.githubusercontent.com/4207677/79627472-3e447380-8158-11ea-92ce-65d4ba72a101.png)
