### ISSUE TITLE
Investigate slowness when adding many members to an institution and errors on Request Membership

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#490]

**Comment by sirmspencer** [comment]
I think the errors are from when the backend is slow to respond to the request, and then UI does not show a loading signal of any sort.  The user then submits duplicate requests.

**Comment by sirmspencer** [comment]
There are two main reasons for this.
1. For institution with a large number of projects, it takes too long to update them all.  Other features like delete project, add imagery, add member, etc wont get sent to the server until all the requests for project stats are loaded. Change the way the project stats are polled so that they lazy load.  The simplest way to do this is to not load the stats until the user puts their mouse over the project.
2. The entire institution information with member list is in the response for each call to add a member.  In PostgresUsers.java change `return getInstitutionById(institutionId);` to `return "";` in  updateInstitutionRole and requestInstitutionMembership

**Comment by sirmspencer** [comment]
Split into #663 #661 #750
