### ISSUE TITLE
Add Skywatch imagery (aggregator) to Add Imagery dropdown

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#542]

**Comment by sirmspencer** [comment]
*** Admin Issues
   - How is SkyWatch integration being funded?
   - Where does it fit in our high-level project priorities?
   - Send out a user interest survey to see how many users want us to integrate SkyWatch imagery (Matt's suggestion)
*** Technical Issues
   - Read the docs and download my developer API key from https://dashboard.skywatch.co [[mu4e:msgid:2d6f.327230a.m1.fde17e90-d2a2-11ea-a317-525400593a2d.173a167e4f9@sender.zohocrm.com][email]] (I'm currently on the free, low-resolution Test Plan)
   - Add a SkyWatch type to the Add Imagery component
   - Get API for account and API key creation, modification, deletion from SkyWatch technical representatives
   - Use EarthCache preview API to show the imagery being requested on an overview map before purchase
   - Use EarthCache pricing API to create a cost per project chart to compare SkyWatch, SecureWatch, and Planet Monthly/Daily options.
   - Add a price calculator to the Create Project page to calculate the SkyWatch imagery cost and request confirmation
   - Send a batch request for all of the plots' imagery at project creation time because this can take a long time
   - Store all the GeoTIFFs (or the Amazon S3 GeoTIFFs links) in the CEO DB and associate them with the project
   - Use geotiff.js on the Collection page to load these images into the web map
   - For medium resolution imagery (3m-10m?), we can make no-cost queries for image metadata to get available dates
   - We can make on-the-fly queries for a particular imagery date, but this may be very slow. We need to test this.
   - Once the service is integrated, upgrade my API key to a paid plan to access higher-resolution imagery
