### ISSUE TITLE
Convert jquery date picker to input type=date to eliminate dependency on jquery-ui and jquery.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#563]

**Comment by rfontanarosa** [comment]
jQuery UI date picker is used only in widget-layout-editor.js.
Using a HTML 5 alternative (or a React alternative) makes the following files useless:
- /css/jquery-ui.css
- /css/datepicker.css
- /js/jquery-ui.min.js

**Comment by rfontanarosa** [comment]
As form validation, HTML 5 has some issues like date format dependency and browser different implementations.
Something we can do is using a custom version of jQuery UI which includes only datepicker instead of ALL its features.
OTHERWISE seems there is no a valid datepicker alternative and removing jQuery and jQuery UI dependency is a big improvement, so I'll proceed using HTML input date.
