### ISSUE TITLE
Add an option to the dual imagery widget to set the default as swipe or opacity.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#674]

**Comment by billyz313** [comment]
It seems that the widget UI is confusing to the user as well, so I will fix that, likely by changing the button to a toggle switch.  I will also have to add a state for default that the admin can select when setting the widget up.  To remain backward compatible I will just store Swipe_As_Default = true, if they want the new configuration otherwise nothing will be set and it will render the current way which is Opacity as default.
